version: '3.8'

services:
  gb28181-simulator:
    build: .
    container_name: gb28181-camera-simulator
    # network_mode: host
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./config:/app/config
      - ./media:/app/media
      - ./logs:/app/logs
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - "8000:8000"
      - "5060:5060/udp"
      - "30000-30100:30000-30100/udp"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
